# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RickAndMorty' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RickAndMorty
   pod 'Moya/RxSwift', '~> 14.0'
   pod 'Kingfisher', '~> 7.0'

  target 'RickAndMortyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RickAndMortyUITests' do
    # Pods for testing
  end

end
